### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by DLwbm123** [Ha0Tang/AttentionGAN#1]
Hi! The dicriminator of AttentionGAN in your implementation is not the case in your paper. There is no "mask_A" or "mask_B" as input to discriminator. It is different from your paper where claimed "where DY A aims to distinguish between the generated image pairs [My;GX!Y (x)] and the real image pairs [My; y]." Can you explain this?

**Comment by yXiangXiong** [comment]
> Hi! The dicriminator of AttentionGAN in your implementation is not the case in your paper. There is no "mask_A" or "mask_B" as input to discriminator. It is different from your paper where claimed "where DY A aims to distinguish between the generated image pairs [My;GX!Y (x)] and the real image pairs [My; y]." Can you explain this?
hi, have you finished the code of the dicriminator? I want to use [My * Gx->y(x)] and [My * y] to be the input of disciminator, is this wrong ？

**Comment by Ha0Tang** [comment]
@DLwbm123 @yXiangXiong Hi, you can create another discriminator, with the generated image and the learned attention mask as input.

**Comment by yXiangXiong** [comment]
Hi, thank you. I will do some experiment about that.
