### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by pytyeah** [Ha0Tang/AttentionGAN#10]
Thanks for your great work! 
But I can not download your pretrained model, could you please upload it to baidu cloud or Google cloud? Or email it to me ? pytyeah@163.com
Thanks a lot!!

**Comment by Ha0Tang** [comment]
Have you tried this [script](https://github.com/Ha0Tang/AttentionGAN#generating-images-using-pretrained-model), I think it should be work. Please let me know if you have any further questions.
