### ISSUE TITLE
Model loss discriminator loss drops to 0 

### ISSUE THREAD

**Issue by stqc** [Ha0Tang/AttentionGAN#11]
Firstly can I just say this that your paper is well written and really simple to understand. Taking references from your code I recreated the implementation in a jupyter notebook but I have come to notice that no matter what dataset I try (tried monet2photo, iPhone2dslr , selfie2anime and horse2zebra) after a few epochs when it seems like the model is starting to generate desired results the discriminator loss drops to 0 all of a sudden and the image produced is from the same domain rather than the previously outputted. I was using the default settings for every dataset (if needed I’ll upload the notebook too) 
Thanks!

**Comment by Ha0Tang** [comment]
Thanks for your interest in our work:)

How many epochs did you train to the discriminator loss to 0? Have you run our code successfully before? Can you share the loss log and the generated images?

**Comment by stqc** [comment]
@Ha0Tang 
I unfortunately don't have the entire loss log but on the selfie2anime dataset it was after epoch 9 the loss dropped to 0. I have attached the output images.
thanks!
![Screenshot from 2020-06-17 02-36-12](https://user-images.githubusercontent.com/42732801/84828297-7a566080-b043-11ea-8c52-8646c4fc3a7e.png)

Output at epoch 9
![0009_3400_progress_A](https://user-images.githubusercontent.com/42732801/84828379-98bc5c00-b043-11ea-8cba-ede805c0767c.png)
![0009_3400_progress_B](https://user-images.githubusercontent.com/42732801/84828384-99ed8900-b043-11ea-969b-1262d0f2c802.png)

output at epoch 10
![0010_3400_progress_A](https://user-images.githubusercontent.com/42732801/84828446-b2f63a00-b043-11ea-9ca6-68fe63352552.png)
![0010_3400_progress_B](https://user-images.githubusercontent.com/42732801/84828449-b4276700-b043-11ea-889f-4573ea16bae6.png)

**Comment by Ha0Tang** [comment]
What `loss_pix_A` and `loss_pix_B` stand for?

**Comment by stqc** [comment]
` GAN loss
        fake_B, mask_B, temp_B = netG_A2B(real_A)
        recovered_A, _, _ = netG_B2A(fake_B)
        pred_fake_B = netD_B(fake_B)

        loss_cycle_ABA = criterion_cycle(recovered_A, real_A)
        loss_GAN_A2B = criterion_GAN(pred_fake_B, target_real)
        loss_pix_A = criterion_identity(fake_B, real_A)

        fake_A, mask_A, temp_A = netG_B2A(real_B)
        recovered_B, _, _  = netG_A2B(fake_A)
        pred_fake_A = netD_A(fake_A)

        loss_cycle_BAB = criterion_cycle(recovered_B, real_B)
        loss_GAN_B2A = criterion_GAN(pred_fake_A, target_real)
        loss_pix_B = criterion_identity(fake_A, real_B) `

This was taken from the train.py that was uploaded by you. I have used the exact code just in a jupyter notebook

**Comment by Ha0Tang** [comment]
I got it. You are using the v1 code, which can only handle face translation. I strongly suggest you use the v2 code [here](https://github.com/Ha0Tang/AttentionGAN/blob/master/models/attention_gan_model.py) since it can handle all the tasks. The corresponding paper is [here](https://128.84.21.199/abs/1911.11897).

**Comment by stqc** [comment]
@Ha0Tang thank you ! Can i use the same logic from train.py ? I’ll post an update tomorrow! :)

**Comment by Ha0Tang** [comment]
Yes, you can.

**Comment by Ha0Tang** [comment]
I will close this issue, if you have any further questions, please open another one.
