### ISSUE TITLE
Does the repo contain the implemention of Framework of the proposed attention-guided generation scheme I

### ISSUE THREAD

**Issue by ganyibo** [Ha0Tang/AttentionGAN#17]
Does the repo contain the implemention of Framework of the proposed attention-guided generation scheme I？？？

**Comment by Ha0Tang** [comment]
Yes

**Comment by Ha0Tang** [comment]
https://github.com/Ha0Tang/AttentionGAN/tree/master/AttentionGAN-v1

**Comment by Ha0Tang** [comment]
https://github.com/Ha0Tang/AttentionGAN/tree/master/AttentionGAN-v1-multi
