### ISSUE TITLE
Attention-Guided Adversarial Loss.

### ISSUE THREAD

**Issue by xuxiaochun025** [Ha0Tang/AttentionGAN#2]
you mention that We propose the attention-guided adversarial loss for training the attentionguide discriminators.But in the code seems that you didn't apply that.

**Comment by Ha0Tang** [comment]
Hi, please refer to this answer https://github.com/Ha0Tang/AttentionGAN/issues/1#issuecomment-535037564.

**Comment by xuxiaochun025** [comment]
Thank you
