### ISSUE TITLE
Checkpoints Missing After Successful Training

### ISSUE THREAD

**Issue by DIMPLY** [Ha0Tang/AttentionGAN#23]
I used the repo to work on horse2zebra dataset as a test. However, after finishing 60 epochs, although the logs (see below) said multiple .pt files were saved to ./chackpoints, nothing is actually shown there.

```
saving the model at the end of epoch 60, iters 80160
End of epoch 60 / 60 	 Time Taken: 444 sec
```

I used exactly the same command line in `scripts/train_attentiongan.sh` -- basically copied it to Colab.

I briefly checked the code and believe the checkpoints should have been saved to the default path, because I didn't specify the flags, just like in `scripts/train_attentiongan.sh`.

Did anyone encountered the same problem?

**Comment by Ha0Tang** [comment]
please refer to [this line](https://github.com/Ha0Tang/AttentionGAN/blob/68a478a944bb45d288d67f99fe110ddf087fd84d/options/train_options.py#L24)

**Comment by DIMPLY** [comment]
It was probably a problem of syncing in Colab. I was able to find the checkpoints in its linux command line, but not in the left tree-veiw.
