### ISSUE TITLE
attention-guided discriminator

### ISSUE THREAD

**Issue by zhang-lingyun** [Ha0Tang/AttentionGAN#3]
did you use the attention-guided discriminator you mentioned in your paper? I can`t find it in your code.

**Comment by Ha0Tang** [comment]
Please refer to here https://github.com/Ha0Tang/AttentionGAN/issues/1#issuecomment-535037564

**Comment by zhang-lingyun** [comment]
Thanks,I get it. Anthor question: have you test your model to other datasets like the horese2zebra in cycleGAN ? I did that using your default setting and get very bad results. Can you give me some suggestions? Thank you in advance.

**Comment by Ha0Tang** [comment]
I tried in the extension journal paper. The paper and its code will be available about this week, please stay tuned with us. Thanks.
