### ISSUE TITLE
experimental on RaFD dataset like Fig. 8

### ISSUE THREAD

**Issue by Johnson-yue** [Ha0Tang/AttentionGAN#4]
Hi, thank you for your sharing . you paper so clear and have many detail about experimental ,this is very important !! I want to reimplement Fig 8 preformance but in your code , I do not find any conditional D or G. 

Would you supply about Fig 8 code ? or some detailed architcuture? Thank your

**Comment by Ha0Tang** [comment]
For Fig 8, we adopt the framework of 'StarGAN + the proposed AttentionGAN-v1'.

**Comment by Johnson-yue** [comment]
This part code can be find in this repo？？

**Comment by Ha0Tang** [comment]
Sorry, the code is not released in this repo so far, I will upload it later as you required.

**Comment by Johnson-yue** [comment]
Thank you very much

**Comment by Ha0Tang** [comment]
@Johnson-yue  please refer to https://github.com/Ha0Tang/AttentionGAN/tree/master/AttentionGAN-v1-multi

**Comment by Johnson-yue** [comment]
@Ha0Tang you are so Nice ,and very good about ReadMe, thank you

**Comment by sparshgarg23** [comment]
@Ha0Tang  Thanks for releasing the code.I was looking at the solver and model.It's quite similar to the one in StarGAn.Could you let me know in which script attention gan is being used?
