### ISSUE TITLE
How many epochs do you set up in your article?

### ISSUE THREAD

**Issue by peachis** [Ha0Tang/AttentionGAN#5]
Thank you for sharing! You have proposed an inspiring method on unpaired image translation.
there is a little question, how many epochs do you set up in your article? Cause I download your pre-trained horse2zebra model which has trained 60 epochs, but the results are not so well as your articles'. 

BTW, maybe there is a spelling mistake in your markdown home page, this is, 'Ecaluation Code' maybe indicate 'evaluation code'.

Thx again.

**Comment by Johnson-yue** [comment]
It default train configuration is 200 epoch， but it too long for training， so I dont retrain

**Comment by Ha0Tang** [comment]
I find that our model is easy to converge, so there is usually no need to train 200 epochs. I will provide more training details this week.

**Comment by peachis** [comment]
Waiting for your improvements!

**Comment by Ha0Tang** [comment]
Hi, we observe that our model can converge around 60 epochs on most datasets, so we adopt `--niter 60 --niter_decay 0`. Moreover, to speed up training, we set `--batch_size 4`, however, we observe that smaller batch size usually get better performance. These training details and more results (e.g., zebra2horse, orange2apple, and multi-domain image translation) are updated in this repo.

**Comment by Ha0Tang** [comment]
The pre-trained models also have been updated. Now I am closing this issue. If you have any questions please open a new one.
