### ISSUE TITLE
Does the attention-guided discriminator take the attention masks as input?

### ISSUE THREAD

**Issue by JuiChang** [Ha0Tang/AttentionGAN#7]
Does the attention-guided discriminator take the attention masks as input as the paper mentioned (neither NLayerDiscriminator or PixelDiscriminator do)? If so, where is the corresponding code?
Thanks!

**Comment by Ha0Tang** [comment]
Thanks for reporting this to me. I will investigate this issue and get back to you as soon as possible.

**Comment by Ha0Tang** [comment]
Attention-guided discriminator only used in the generation scheme I, where the input domain and the output domain have lots of similarities. For the code of the generation scheme I, please refer to [here](https://github.com/Ha0Tang/AttentionGAN/tree/master/AttentionGAN-v1). Moreover, the [updated paper](https://128.84.21.199/abs/1911.11897) and [the discussion](https://github.com/Ha0Tang/AttentionGAN/issues/1) will help too.
